import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const SUPABASE_URL="https://scyhmxfksqlwjkqhlama.supabase.co";
const SUPABASE_ANON_KEY="sb_publishable_StNVl1zqzZE_bsetnfi8mA_jl9TBFyI";
const configured=!SUPABASE_URL.includes("PASTE_")&&!SUPABASE_ANON_KEY.includes("PASTE_");
const supabase=configured?createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null;
const $=s=>document.querySelector(s), esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
async function news(){const b=$("#newsList");if(!configured){b.innerHTML="<article><h3>Website siap dikonfigurasi</h3><p>Masukkan Project URL dan Publishable/Anon Key Supabase di app.js.</p></article>";return}const{data}=await supabase.from("berita").select("judul,ringkasan,created_at").eq("diterbitkan",true).order("created_at",{ascending:false}).limit(6);b.innerHTML=data?.length?data.map(x=>`<article><h3>${esc(x.judul)}</h3><p>${esc(x.ringkasan||"Informasi BPD Desa Kendalserut.")}</p></article>`).join(""):"<article><h3>Belum ada berita</h3><p>Berita BPD akan tampil di sini.</p></article>"}
$("#aspForm").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),m=$("#aspMsg");if(!configured){m.textContent="Supabase belum dikonfigurasi.";return}m.textContent="Mengirim...";let{data,error}=await supabase.from("aspirasi").insert({nama:f.get("nama")||null,dusun:f.get("wilayah")||null,whatsapp:f.get("whatsapp")||null,kategori:f.get("kategori"),isi_aspirasi:f.get("isi"),anonim:f.get("anonim")==="on"}).select("nomor_tiket").single();if(error){m.textContent="Gagal: "+error.message;return}e.target.reset();m.innerHTML=`Berhasil. Nomor tiket: <b>${esc(data.nomor_tiket)}</b>. Simpan nomor ini.`}
$("#checkForm").onsubmit=async e=>{e.preventDefault();let t=new FormData(e.target).get("ticket").trim().toUpperCase(),b=$("#checkResult");if(!configured){b.innerHTML='<div class="result">Supabase belum dikonfigurasi.</div>';return}let{data}=await supabase.from("aspirasi").select("nomor_tiket,kategori,status,tanggapan,created_at").eq("nomor_tiket",t).maybeSingle();b.innerHTML=data?`<div class="result"><b>${esc(data.nomor_tiket)}</b><p>Kategori: ${esc(data.kategori)}</p><p>Status: <span class="status">${esc(data.status)}</span></p><p>${data.tanggapan?"Tanggapan BPD: "+esc(data.tanggapan):"Belum ada tanggapan."}</p></div>`:'<div class="result">Nomor tiket tidak ditemukan.</div>'}
async function admin(){let a=$("#adminDash"),l=$("#logoutBtn");if(!configured)return;if(!supabase)return;let{data:{user}}=await supabase.auth.getUser();if(!user){a.classList.add("hidden");l.classList.add("hidden");return}let{data:p}=await supabase.from("admin_profiles").select("nama_lengkap,jabatan").eq("id",user.id).maybeSingle();if(!p){a.innerHTML="<div class='panel'>Akun bukan admin BPD.</div>";a.classList.remove("hidden");return}l.classList.remove("hidden");a.classList.remove("hidden");let{data:r}=await supabase.from("aspirasi").select("*").order("created_at",{ascending:false});r=r||[];a.innerHTML=`<div class="panel"><h3>Dashboard ${esc(p.nama_lengkap)}</h3><p>Total aspirasi: <b>${r.length}</b></p><div style="overflow:auto"><table><tr><th>Tiket</th><th>Pelapor</th><th>Kategori</th><th>Status</th><th>Tanggapan</th><th>Aksi</th></tr>${r.map(x=>`<tr><td>${esc(x.nomor_tiket)}</td><td>${x.anonim?"Anonim":esc(x.nama||"Masyarakat")}</td><td>${esc(x.kategori)}</td><td><select class="st" data-id="${x.id}"><option ${x.status=="Diterima"?"selected":""}>Diterima</option><option ${x.status=="Diproses"?"selected":""}>Diproses</option><option ${x.status=="Ditindaklanjuti"?"selected":""}>Ditindaklanjuti</option><option ${x.status=="Selesai"?"selected":""}>Selesai</option></select></td><td><textarea class="tg" data-id="${x.id}">${esc(x.tanggapan||"")}</textarea></td><td><button class="save" data-id="${x.id}">Simpan</button></td></tr>`).join("")}</table></div></div>`;document.querySelectorAll(".save").forEach(b=>b.onclick=async()=>{let id=b.dataset.id,s=document.querySelector(`.st[data-id="${id}"]`).value,t=document.querySelector(`.tg[data-id="${id}"]`).value;let{error}=await supabase.from("aspirasi").update({status:s,tanggapan:t}).eq("id",id);alert(error?error.message:"Tersimpan");if(!error)admin()})}
$("#loginForm").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),m=$("#loginMsg");if(!configured){m.textContent="Konfigurasi Supabase dulu.";return}let{error}=await supabase.auth.signInWithPassword({email:f.get("email"),password:f.get("password")});m.textContent=error?error.message:"Login berhasil.";if(!error)admin()}
$("#logoutBtn").onclick=async()=>{await supabase.auth.signOut();admin()};$("#navBtn").onclick=()=>{let n=$("#nav");n.style.display=n.style.display==="flex"?"none":"flex"};news();admin();